import assert from "node:assert/strict"
import { mkdir } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { COMMAND_METADATA } from "../src/commands/metadata"

interface PackageManifest {
  version: string
}

const root = resolve(import.meta.dir, "..")
const manifest = (await Bun.file(resolve(root, "package.json")).json()) as PackageManifest

function markdownCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ")
}

function commandIndex(): string {
  const rows = COMMAND_METADATA.map(
    ({ path, summary }) => `| \`tt ${markdownCell(path.join(" "))}\` | ${markdownCell(summary)} |`,
  ).join("\n")

  return `# Generated command index

> Generated from \`src/commands/metadata.ts\`. Run \`bun run docs:generate\` after changing command
> metadata; do not edit this file directly.

| Command | Summary |
|---|---|
${rows}
`
}

function roff(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll("-", "\\-")
}

function manPage(): string {
  const commands = COMMAND_METADATA.map(
    ({ path, summary }) => `.TP
.B ${roff(`tt ${path.join(" ")}`)}
${roff(summary)}.`,
  ).join("\n")

  return `.\\" Generated from src/commands/metadata.ts; do not edit directly.
.TH TT 1 "2026-07-13" "tt ${roff(manifest.version)}" "TickTick CLI Manual"
.SH NAME
tt \\- agent-first TickTick command-line interface
.SH SYNOPSIS
.B tt
.RI [ global-options ]
.I command
.RI [ command-options ]
.SH DESCRIPTION
.B tt
provides deterministic, headless access to TickTick and capability-gated
Dida365 operations. Use \\-\\-json and \\-\\-no-input for automation.
Structured results are written to stdout and diagnostics to stderr.
.SH GLOBAL OPTIONS
.TP
.B \\-\\-json
Emit a versioned JSON envelope.
.TP
.B \\-\\-no-input
Disable prompts, pickers, editors, and browser launches.
.TP
.B \\-\\-profile NAME
Select a profile for this invocation.
.TP
.B \\-\\-fresh, \\-\\-stale-ok, \\-\\-offline
Select one cache freshness policy.
.TP
.B \\-\\-dry-run
Normalize and report a mutation without sending it.
.TP
.B \\-\\-yes
Confirm a destructive non-interactive operation without selecting defaults.
.SH COMMANDS
${commands}
.SH EXIT STATUS
0 indicates success; 2 invalid input; 3 missing authentication or capability;
4 not found or ambiguous; 5 conflict or partial failure; 6 network, rate limit,
or unknown write outcome; 7 protocol drift; and 8 local configuration, cache,
or storage failure.
.SH FILES
Configuration, credentials, cache, and logs use separate platform-correct
locations under the stable application identifier ticktickcli. Use tt doctor
and tt config instead of relying on a hard-coded path.
.SH SEE ALSO
The package documentation includes authentication.md, configuration.md, and
commands.md.
`
}

const outputs = new Map([
  [resolve(root, "docs/command-index.md"), commandIndex()],
  [resolve(root, "docs/man/tt.1"), manPage()],
])

if (process.argv.includes("--print-index")) {
  process.stdout.write(commandIndex())
} else if (process.argv.includes("--print-man")) {
  process.stdout.write(manPage())
} else if (process.argv.includes("--check")) {
  const stale: string[] = []
  for (const [path, expected] of outputs) {
    const file = Bun.file(path)
    if (!(await file.exists()) || (await file.text()) !== expected) {
      stale.push(path.replace(`${root}/`, ""))
    }
  }
  assert.deepEqual(stale, [], `generated documentation is stale: ${stale.join(", ")}`)
} else {
  for (const [path, contents] of outputs) {
    await mkdir(dirname(path), { recursive: true })
    await Bun.write(path, contents)
  }
}
